url: https://jimmythompson.co.uk
permalink: /blog/:title/

highlighter: rouge
sass:
  sass_dir: style
  style: compressed

name: "Jimmy Thompson - Software Developer"
description: "The personal website and blog of Jimmy Thompson, a software developer based in London"

gravatar: //www.gravatar.com/avatar/73083e7e6bda1576bf6ea9e5be037c78
twitter: jimmythompson
github: jimmythompson
medium: jimmythompson
facebook: JimmyThompsonUK
email: jimmy@jimmythompson.co.uk

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE
  - README.md
  - Rakefile
  - banner.txt
  - bin
  - gems/
  - vendor/
