url: https://jimmythompson.co.uk
permalink: /blog/:title/

highlighter: rouge
sass:
  sass_dir: style
  style: compressed

name: "Jimmy Thompson - Software Engineer"
description: "Hi, I'm Jimmy, a software engineer based in London"

twitter: https://twitter.com/jimmythompson
github: https://github.com/jimmythompson
medium: https://medium.com/@jimmythompson
stackoverflow: https://stackoverflow.com/users/1162899/jimmy-thompson

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE
  - README.md
  - Rakefile
  - banner.txt
  - bin
  - gems/
  - vendor/
