url: https://jimmythompson.co.uk
permalink: /blog/:title/

highlighter: rouge
sass:
  sass_dir: style
  style: compressed

name: "Jimmy Thompson - London-based Software Engineer"
description: "Hi, I'm Jimmy, an engineering leader based in London. Currently at Freetrade, previously at ThoughtWorks. I build stuff and talk about it sometimes."

twitter: https://twitter.com/jimmythompson
github: https://github.com/jimmythompson
medium: https://medium.com/@jimmythompson
stackoverflow: https://stackoverflow.com/users/1162899/jimmy-thompson
linkedin: https://www.linkedin.com/in/jimmythompsonuk/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENCE
  - README.md
  - Rakefile
  - banner.txt
  - bin
  - gems/
  - vendor/
