url: https://jimmythompson.co.uk
permalink: /blog/:title/

exclude: [ "Gemfile", "Gemfile.lock", "LICENCE", "README.md", "Rakefile", "banner.txt", "bin" ]

highlighter: rouge
sass:
  sass_dir: style
  style: compressed

name: "Jimmy Thompson - Software Developer"
description: "The personal website and blog of Jimmy Thompson, a software developer based in London"

twitter: jimmythompson
github: jimmythompson
medium: jimmythompson
facebook: JimmyThompsonUK
email: jimmy@jimmythompson.co.uk
