markdown: rdiscount
highlighter: rouge
permalink: /blog/:title
rdiscount:
  extensions: [smart]

url: https://jimmythompson.co.uk
name: "Jimmy Thompson - Software Developer"
description: "The personal website and blog of Jimmy Thompson, a software developer based in London"
twitter: jimmythompson
github: jimmythompson
facebook: JimmyThompsonUK
email: jimmy@jimmythompson.co.uk
